[project]
name = "django-multi-tenant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django==5.1.9",
    "django-filter==25.1",
    "django-tenant-users==2.1.1",
    "django-tenants==3.7.0",
    "djangorestframework==3.16.0",
    "markdown==3.8",
    "psycopg2-binary==2.9.10",
    "python-dotenv>=1.2.1",
]
