# Generated by Django 5.1.9 on 2026-01-21 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def convert_id_to_uuid(apps, schema_editor):
    """Convert existing bigint IDs to UUIDs"""
    UserInvitation = apps.get_model('tenants', 'UserInvitation')
    
    # Store old data
    old_invitations = list(UserInvitation.objects.all().values())
    
    # Clear the table
    UserInvitation.objects.all().delete()
    
    # Recreate with new UUIDs
    for invitation_data in old_invitations:
        invitation_data.pop('id')  # Remove old ID
        UserInvitation.objects.create(**invitation_data)


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_user_first_name_user_is_tenant_admin_user_last_name_and_more'),
    ]

    operations = [
        # First, remove the old primary key constraint
        migrations.RunSQL(
            "ALTER TABLE tenants_userinvitation DROP CONSTRAINT tenants_userinvitation_pkey;",
            reverse_sql="ALTER TABLE tenants_userinvitation ADD CONSTRAINT tenants_userinvitation_pkey PRIMARY KEY (id);"
        ),
        
        # Add new UUID column
        migrations.AddField(
            model_name='userinvitation',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        
        # Convert data
        migrations.RunPython(convert_id_to_uuid, migrations.RunPython.noop),
        
        # Remove old ID column
        migrations.RemoveField(
            model_name='userinvitation',
            name='id',
        ),
        
        # Rename new column to id
        migrations.RenameField(
            model_name='userinvitation',
            old_name='uuid_id',
            new_name='id',
        ),
        
        # Add primary key constraint
        migrations.RunSQL(
            "ALTER TABLE tenants_userinvitation ADD CONSTRAINT tenants_userinvitation_pkey PRIMARY KEY (id);",
            reverse_sql="ALTER TABLE tenants_userinvitation DROP CONSTRAINT tenants_userinvitation_pkey;"
        ),
        
        # Update other fields
        migrations.AlterField(
            model_name='userinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='userinvitation',
            unique_together={('tenant', 'email')},
        ),
    ]