# Generated by Django 5.1.9 on 2026-02-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_userinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_tenant_admin',
        ),
    ]
