# core/settings.py
"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# Import standard libraries
import os
from pathlib import Path
from typing import Any

# Import django libraries and modules
from django.contrib.messages import constants as messages

# Import third-party libraries and modules
from dotenv import load_dotenv

# Import local modules
from utils.logger import get_logging_config

# Project base directory
BASE_DIR: Path = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(dotenv_path=BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY: str = os.getenv(key="SECRET_KEY", default="your-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG: bool = str(os.getenv(key="DEBUG", default="True")).lower() in ("true", "1", "t")

# Set console log level from environment variable, defaulting to INFO
CONSOLE_LOG_LEVEL: str = os.getenv(key="CONSOLE_LOG_LEVEL", default="INFO")

ALLOWED_HOSTS = [
    host.strip("\"[]'")
    for host in os.getenv(key="ALLOWED_HOSTS", default="*").split(sep=",")
]

# Application definition (public/shared apps only)
SHARED_APPS = [
    "django_tenants",  # django-tenants
    "hijack",  # Impersonation
    "crispy_forms",  # Crispy forms for forms rendering
    "crispy_bootstrap5",  # Crispy forms for bootstrap 5
    "django_structlog",  # Structured logging
    "core.apps.CoreConfig",  # local core app
    "core.apps.CustomAdminConfig",  # Custom admin configuration
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",  # REST framework for API
    "django_filters",  # Django filtering querysets
    "tenants.apps.TenantsConfig",  # local tenants app
    "accounts.apps.AccountsConfig",  # local accounts app
    "blog.apps.BlogConfig",  # local blog app
    "tenant_users.tenants",  # django-tenant-users for shared user pool
]

# Application definition (tenant apps only)
TENANT_APPS = [
    "tenant_users.permissions",  # django-tenant-users for per-tenant permissions
    "tasks.apps.TasksConfig",  # local tasks app
]

# Application definition (public/shared apps and tenant apps)
INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

# Middleware
MIDDLEWARE = [
    "django_tenants.middleware.main.TenantMainMiddleware",  # django-tenants middleware for tenant resolution
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # whitenoise for static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_structlog.middlewares.RequestMiddleware",  # django-structlog middleware for request logging
    "hijack.middleware.HijackUserMiddleware",  # Hijack middleware for impersonation
    "core.middleware.PublicTenantAccessMiddleware",  # custom middleware inheriting from tenant-users
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Bootstrap 5 message tags
MESSAGE_TAGS = {
    messages.ERROR: "danger",
}

# URLs
ROOT_URLCONF = "core.urls"
PUBLIC_SCHEMA_URLCONF = "core.urls_public"

# Templates
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.public_domain_context",  # custom context processor
            ],
        },
    },
]

# WSGI application
WSGI_APPLICATION = "core.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": os.getenv(key="POSTGRES_DB"),
        "USER": os.getenv(key="POSTGRES_USER"),
        "PASSWORD": os.getenv(key="POSTGRES_PASSWORD"),
        "HOST": os.getenv(key="POSTGRES_HOST"),
        "PORT": os.getenv(key="POSTGRES_PORT"),
    }
}

# Django-tenants settings
DATABASE_ROUTERS = ["django_tenants.routers.TenantSyncRouter"]

# Show public tenant (no other tenant found)
SHOW_PUBLIC_IF_NO_TENANT_FOUND = False

BASE_DOMAIN: str = os.getenv(key="BASE_DOMAIN", default="lvh.me")

# Allow session cookies to be shared across subdomains (e.g., demo1.lvh.me and demo2.lvh.me)
# This requires to access the site via BASE_DOMAIN
SESSION_COOKIE_DOMAIN: str = f".{BASE_DOMAIN}"
CSRF_COOKIE_DOMAIN: str = f".{BASE_DOMAIN}"

PUBLIC_SCHEMA_NAME = "public"

# Reserved subdomains that cannot be registered by tenants
TENANT_SUBDOMAIN_RESERVED_NAMES: list[str] = [
    "public",
    "www",
    "admin",
    "api",
    "blog",
    "dashboard",
    "support",
    "help",
    "mail",
    "accounts",
    "tasks",
    "tenants",
    "tenant",
    "task",
    "project",
    "projects",
    "articles",
    "article",
    "django",
    "rest",
    "filters",
    "crispy",
    "users",
    "permissions",
    "auth",
    "messages",
    "static",
    "media",
    "templates",
    "search",
    "invitations",
    "accept",
    "decline",
    "login",
    "logout",
    "signup",
    "onboarding",
    "index",
    "users",
    "edit",
    "remove",
    "hijack",
    "core",
]

AUTH_USER_MODEL = "tenants.User"

TENANT_MODEL = "tenants.Tenant"

TENANT_DOMAIN_MODEL = "tenants.Domain"

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Django-tenant-users settings
TENANT_USERS_DOMAIN: str = BASE_DOMAIN

AUTHENTICATION_BACKENDS = [
    "tenant_users.permissions.backend.UserBackend",
]

# Django Hijack Settings
HIJACK_ALLOW_GET_REQUESTS = True
HIJACK_LOGOUT_REDIRECT_URL = "/admin/tenants/user/"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"  # Static files for each root app

STATICFILES_DIRS = [
    BASE_DIR / "static"
]  # Static files directory globally accessible by all apps in the project while in development

STATIC_ROOT = (
    BASE_DIR / "staticfiles"
)  # All static files will be collected here for deployment

# WhiteNoise configuration for production
if not DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Media files (user uploaded files)
MEDIA_ROOT: Path = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email configuration for password reset
# EMAIL_BACKEND: str | None = os.environ.get("EMAIL_BACKEND")
# EMAIL_HOST: str | None = os.environ.get("EMAIL_HOST")
# EMAIL_PORT: str | None = os.environ.get("EMAIL_PORT")
# EMAIL_USE_TLS: str | None = os.environ.get("EMAIL_USE_TLS")
# EMAIL_HOST_USER: str | None = os.environ.get("EMAIL_USER")
# EMAIL_HOST_PASSWORD: str | None = os.environ.get("EMAIL_PASS")
# DEFAULT_FROM_EMAIL: str | None = os.environ.get("EMAIL_USER")

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # for development

# Redirects after login and logout
LOGIN_REDIRECT_URL = "index"
LOGOUT_REDIRECT_URL = "index"


# Logging configuration
LOGGING: dict[str, Any] = get_logging_config(
    base_dir=BASE_DIR,
    app_names=["accounts", "blog", "tasks", "tenants"],
    console_log_level=CONSOLE_LOG_LEVEL,
)
