# core/settings.py
"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(dotenv_path=BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY: str | None = os.getenv(key="SECRET_KEY", default="your-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG: bool = os.getenv(key="DEBUG", default="True") == "True"

ALLOWED_HOSTS: list[str] = [
    host.strip("\"[]'")
    for host in os.getenv(key="ALLOWED_HOSTS", default="*").split(",")
]

# Application definition (public/shared apps only)
SHARED_APPS = [
    "django_tenants",  # django-tenants
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_filters",
    "tenants.apps.TenantsConfig",  # local tenants app
    "accounts.apps.AccountsConfig",  # local accounts app
    "blog.apps.BlogConfig",  # local blog app
    "tenant_users.permissions",  # django-tenant-users
    "tenant_users.tenants",  # django-tenant-users
]

# Application definition (tenant apps only)
TENANT_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "tenant_users.permissions",  # django-tenant-users
    "tasks.apps.TasksConfig",  # local tasks app
]

# Application definition (public/shared apps and tenant apps)
INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

MIDDLEWARE = [
    "django_tenants.middleware.main.TenantMainMiddleware",  # django-tenants
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # whitenoise for static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "tenant_users.tenants.middleware.TenantAccessMiddleware",  # django-tenant-users
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"
PUBLIC_SCHEMA_URLCONF = "core.urls_public"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.public_domain_context",  # custom context processor
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": os.getenv(key="POSTGRES_DB"),
        "USER": os.getenv(key="POSTGRES_USER"),
        "PASSWORD": os.getenv(key="POSTGRES_PASSWORD"),
        "HOST": os.getenv(key="POSTGRES_HOST"),
        "PORT": os.getenv(key="POSTGRES_PORT"),
    }
}

# Django-tenants settings
DATABASE_ROUTERS = ["django_tenants.routers.TenantSyncRouter"]

BASE_DOMAIN = "localhost"

PUBLIC_SCHEMA_NAME = "public"

AUTH_USER_MODEL = "tenants.User"

TENANT_MODEL = "tenants.Tenant"

TENANT_DOMAIN_MODEL = "tenants.Domain"

# Django-tenant-users settings
TENANT_USERS_DOMAIN = BASE_DOMAIN

AUTHENTICATION_BACKENDS = [
    "tenant_users.permissions.backend.UserBackend",
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"  # Static files for each root app

STATICFILES_DIRS: list[Path] = [
    BASE_DIR / "static"
]  # Static files directory globally accessible by all apps in the project while in development

STATIC_ROOT: Path = (
    BASE_DIR / "staticfiles"
)  # All static files will be collected here for deployment

# WhiteNoise configuration for production
if not DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Media files (user uploaded files)
MEDIA_ROOT: Path = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email configuration for password reset
# EMAIL_BACKEND: str | None = os.environ.get("EMAIL_BACKEND")
# EMAIL_HOST: str | None = os.environ.get("EMAIL_HOST")
# EMAIL_PORT: str | None = os.environ.get("EMAIL_PORT")
# EMAIL_USE_TLS: str | None = os.environ.get("EMAIL_USE_TLS")
# EMAIL_HOST_USER: str | None = os.environ.get("EMAIL_USER")
# EMAIL_HOST_PASSWORD: str | None = os.environ.get("EMAIL_PASS")
# DEFAULT_FROM_EMAIL: str | None = os.environ.get("EMAIL_USER")

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # for development

# Redirects after login and logout
LOGIN_REDIRECT_URL = "index"
LOGOUT_REDIRECT_URL = "index"
