# Generated by Django 5.1.9 on 2026-02-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload a featured image', null=True, upload_to='blog/images/'),
        ),
    ]
